### ISSUE TITLE
Missing brace in for loop?

### ISSUE THREAD

**Issue by TTAliA** [endel/FossilDelta#5]
First just wanna say THANKS! Thanks for writing an API that just works. I expected to have to write only 2 lines of code from a usage stand point to create and apply a delta, and that's exactly what this API offers. Very nice usage interface. A breeze from all the over-engineered crap you usually see out there.

One thing I found is after downloading the source, there's a missing open brace for the for loop in Create(..)? https://github.com/endel/FossilDelta/blob/c52680c9b09105a075711404b01ce5c4da924d34/Source/Delta.cs#L38

Other than that it works great!

**Comment by endel** [comment]
Hi @TTAliA, glad this library is serving some purpose to you! Apparently this problem has been introduced here https://github.com/endel/FossilDelta/pull/4/files

I'm not currently using this project anymore though, the source is not compiling because of this? Do you mind sending a PR fixing this? 

Cheers!
